import { useState } from "react";
import {
  BrainCircuit,
  TrendingUp,
  AlertTriangle,
  Lightbulb,
  BarChart3,
  ExternalLink,
  X,
  Sparkles,
} from "lucide-react";
import { cn, timeAgo } from "@/lib/utils";
import { useFetch } from "@/hooks/useFetch";
import { insightsApi } from "@/lib/api";
import type { AIInsight } from "@/types";

const typeConfig: Record<string, { icon: React.ElementType; label: string; color: string }> = {
  TREND: { icon: TrendingUp, label: "Trend", color: "bg-blue-50 text-blue-700 border-blue-200" },
  ANOMALY: { icon: AlertTriangle, label: "Anomaly", color: "bg-red-50 text-red-700 border-red-200" },
  RECOMMENDATION: { icon: Lightbulb, label: "Recommendation", color: "bg-amber-50 text-amber-700 border-amber-200" },
  PATTERN: { icon: BarChart3, label: "Pattern", color: "bg-violet-50 text-violet-700 border-violet-200" },
};

const severityColors: Record<string, string> = {
  CRITICAL: "bg-red-500 text-white",
  HIGH: "bg-orange-500 text-white",
  MEDIUM: "bg-amber-400 text-white",
  LOW: "bg-slate-400 text-white",
};

const severityBorders: Record<string, string> = {
  CRITICAL: "border-l-red-500",
  HIGH: "border-l-orange-500",
  MEDIUM: "border-l-amber-400",
  LOW: "border-l-slate-300",
};

const typeFilters = [
  { value: "ALL", label: "All Insights" },
  { value: "TREND", label: "Trends" },
  { value: "ANOMALY", label: "Anomalies" },
  { value: "RECOMMENDATION", label: "Recommendations" },
  { value: "PATTERN", label: "Patterns" },
];

export default function InsightsPage() {
  const [typeFilter, setTypeFilter] = useState("ALL");

  const { data: insights, loading, refetch } = useFetch<AIInsight[]>(
    () => insightsApi.getAll(typeFilter !== "ALL" ? { type: typeFilter } : undefined),
    [typeFilter]
  );

  const handleDismiss = async (id: string) => {
    try {
      await insightsApi.dismiss(id);
      refetch();
    } catch {
      // handle error
    }
  };

  const grouped = {
    CRITICAL: insights?.filter(i => i.severity === "CRITICAL") || [],
    HIGH: insights?.filter(i => i.severity === "HIGH") || [],
    MEDIUM: insights?.filter(i => i.severity === "MEDIUM") || [],
    LOW: insights?.filter(i => i.severity === "LOW") || [],
  };

  return (
    <div className="space-y-5">
      {/* Header Card */}
      <div className="rounded-xl border border-slate-200 bg-gradient-to-r from-blue-50 via-indigo-50 to-violet-50 p-5 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white border border-blue-200 shadow-sm">
            <BrainCircuit className="h-5 w-5 text-blue-600" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-slate-900">AI-Powered Insights</h3>
            <p className="text-xs text-slate-600 mt-0.5">
              {insights?.length || 0} active insights generated by the RecoverAI engine
            </p>
          </div>
        </div>
      </div>

      {/* Type Filters */}
      <div className="flex gap-2 overflow-x-auto">
        {typeFilters.map((filter) => (
          <button
            key={filter.value}
            onClick={() => setTypeFilter(filter.value)}
            className={cn(
              "px-3 py-1.5 text-sm font-medium rounded-lg transition-colors whitespace-nowrap",
              typeFilter === filter.value
                ? "bg-blue-600 text-white"
                : "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50"
            )}
          >
            {filter.label}
          </button>
        ))}
      </div>

      {/* Insights */}
      {loading ? (
        <div className="space-y-3">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="h-28 rounded-xl border border-slate-200 bg-white animate-pulse" />
          ))}
        </div>
      ) : insights && insights.length > 0 ? (
        <div className="space-y-4">
          {Object.entries(grouped).map(([severity, items]) =>
            items.length > 0 && (
              <div key={severity}>
                <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2 flex items-center gap-2">
                  <span className={cn("h-2 w-2 rounded-full", severity === "CRITICAL" ? "bg-red-500" : severity === "HIGH" ? "bg-orange-500" : severity === "MEDIUM" ? "bg-amber-400" : "bg-slate-400")} />
                  {severity} ({items.length})
                </h4>
                <div className="space-y-3">
                  {items.map((insight) => {
                    const config = typeConfig[insight.type] || typeConfig.TREND;
                    const TypeIcon = config.icon;

                    return (
                      <div
                        key={insight.id}
                        className={cn(
                          "rounded-xl border border-slate-200 border-l-4 bg-white p-5 shadow-sm transition-all hover:shadow-md",
                          severityBorders[insight.severity]
                        )}
                      >
                        <div className="flex items-start justify-between gap-4">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 mb-2 flex-wrap">
                              <span className={cn("inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold border", config.color)}>
                                <TypeIcon className="h-3 w-3" />
                                {config.label}
                              </span>
                              <span className={cn("px-1.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider", severityColors[insight.severity])}>
                                {insight.severity}
                              </span>
                              <span className="text-[11px] text-slate-400">{timeAgo(insight.createdAt)}</span>
                            </div>
                            <h3 className="text-sm font-semibold text-slate-900 mb-1">{insight.title}</h3>
                            <p className="text-sm text-slate-600 leading-relaxed">{insight.description}</p>

                            {/* Data Chips */}
                            {insight.data && (
                              <div className="flex flex-wrap gap-2 mt-3">
                                {Object.entries(insight.data as Record<string, unknown>).slice(0, 4).map(([key, val]) => (
                                  <span key={key} className="inline-flex items-center gap-1 px-2 py-1 rounded-md bg-slate-50 border border-slate-200 text-[11px] text-slate-600">
                                    <span className="font-medium text-slate-500">{key.replace(/([A-Z])/g, " $1").trim()}:</span>
                                    <span className="font-semibold text-slate-800">{String(val)}</span>
                                  </span>
                                ))}
                              </div>
                            )}
                          </div>

                          {/* Actions */}
                          <div className="flex flex-col gap-2 shrink-0">
                            <button
                              onClick={() => handleDismiss(insight.id)}
                              className="flex h-7 w-7 items-center justify-center rounded-md text-slate-300 hover:text-slate-500 hover:bg-slate-100 transition-colors"
                              title="Dismiss"
                            >
                              <X className="h-4 w-4" />
                            </button>
                            {insight.actionable && insight.actionUrl && (
                              <a
                                href={insight.actionUrl}
                                className="flex h-7 w-7 items-center justify-center rounded-md text-blue-400 hover:text-blue-600 hover:bg-blue-50 transition-colors"
                                title="View related"
                              >
                                <ExternalLink className="h-4 w-4" />
                              </a>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )
          )}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-20 text-slate-400 bg-white rounded-xl border border-slate-200">
          <Sparkles className="h-10 w-10 mb-3 text-slate-300" />
          <p className="text-sm">No insights available</p>
          <p className="text-xs mt-1">AI engine will generate insights as more data flows in</p>
        </div>
      )}
    </div>
  );
}
